package amadeus.cognition;

import amadeus.personality.Speech;

/**
 * Command to display the list of available commands.
 * <p>
 * This command prints the list of commands to the console, providing usage examples.
 * </p>
 */
public class CommandList extends Command
{
    /**
     * Displays the list of available commands to the console.
     * <p>
     * The commands are formatted with usage examples for better readability.
     * The output is generated by the {@link Speech#sayCommands()} method.
     * </p>
     */
    @Override
    public void execute()
    {
        Speech.sayCommands();
    }
}
