package amadeus.cognition;

import amadeus.personality.Speech;

import static amadeus.workspace.TaskList.taskList;

/**
 * Command to display the current list of tasks.
 * <p>
 * This command prints the list of tasks to the console, organized by type.
 * </p>
 */
public class ListCommand extends Command {
    /**
     * Displays the current list of tasks to the console.
     * <p>
     * The tasks are organized by type (Deadlines, Events, ToDos).
     * The output is generated by the {@link Speech#sayList(java.util.ArrayList)} method.
     * </p>
     */
    @Override
    public void execute() {
        Speech.sayList(taskList);
    }
}